/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    courses: Course;
    faqs: Faq;
    testimonials: Testimonial;
    applications: Application;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'he' | 'en') | ('ar' | 'he' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'ar' | 'he' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photos and other files used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and SEO — required in every language.
   */
  alt: string;
  /**
   * Optional visible caption, if the image needs one.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * The academy's current courses.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * Published courses appear on the public site. All three languages are required to publish.
   */
  status: 'draft' | 'published';
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  /**
   * URL-friendly identifier, e.g. "cosmetics-1". Shared across all locales — not translated.
   */
  slug: string;
  title: string;
  /**
   * Used on course cards and listings.
   */
  shortDescription: string;
  /**
   * Full description for the course detail page.
   */
  description?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Additional photos for the course detail page.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Who this course is for.
   */
  audience?: string | null;
  /**
   * Optional override for the course card button. Leave blank for the site default.
   */
  ctaLabel?: string | null;
  /**
   * Modules or stages of the course.
   */
  curriculum?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What a student leaves with.
   */
  outcomes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pricing is not finalized — "On request" is the safe default.
   */
  pricingType: 'exact' | 'startingFrom' | 'range' | 'onRequest' | 'hidden';
  /**
   * The exact price, or the "starting from" amount.
   */
  price?: number | null;
  priceRangeMin?: number | null;
  priceRangeMax?: number | null;
  currency?: ('ILS' | 'USD') | null;
  /**
   * Freeform, e.g. "6 weeks". Leave blank if not finalized.
   */
  duration?: string | null;
  /**
   * Freeform schedule details, once finalized.
   */
  scheduleInfo?: string | null;
  enrollmentState: 'open' | 'closed' | 'comingSoon' | 'full';
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently asked questions shown on the homepage (and, later, course pages).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  status: 'draft' | 'published';
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  /**
   * Optional — leave blank for a general FAQ shown on the homepage.
   */
  relatedCourse?: (number | null) | Course;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Real testimonials only, with explicit consent. Leave this collection empty rather than publish anything unverified.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  status: 'draft' | 'published';
  /**
   * Required before publishing: confirm the person agreed to have their words used publicly.
   */
  consentObtained: boolean;
  /**
   * How/when consent was obtained, e.g. "Written consent via email, 2026-01-14".
   */
  consentNote?: string | null;
  relatedCourse?: (number | null) | Course;
  /**
   * A real name — never invented. Not localized (it is a proper noun).
   */
  authorName: string;
  /**
   * e.g. "Cosmetics 1 graduate" — optional.
   */
  authorRole?: string | null;
  quote: string;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Leads from the website. Never publicly readable.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  status:
    | 'new'
    | 'automatic_followup'
    | 'engaged'
    | 'qualified'
    | 'consultation_booked'
    | 'visited'
    | 'enrolled'
    | 'no_answer'
    | 'follow_up'
    | 'not_now'
    | 'not_interested'
    | 'invalid'
    | 'spam';
  /**
   * Staff member handling this lead.
   */
  assignedTo?: (number | null) | User;
  /**
   * Scheduled consultation or visit, once booked.
   */
  consultationAt?: string | null;
  /**
   * e.g. "homepage", "instagram", "referral".
   */
  source?: string | null;
  name: string;
  phone: string;
  email?: string | null;
  preferredLanguage: 'ar' | 'he' | 'en';
  interestedCourse?: (number | null) | Course;
  /**
   * The lead's own message, as submitted.
   */
  message?: string | null;
  /**
   * Staff-only notes — never shown to the lead.
   */
  internalNotes?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  /**
   * When the lead agreed to the privacy policy.
   */
  privacyConsentAt: string;
  /**
   * Which privacy policy version was in effect, e.g. "v1".
   */
  privacyPolicyVersion?: string | null;
  /**
   * Separate, optional opt-in — never bundled with the privacy consent above.
   */
  marketingConsent?: boolean | null;
  marketingConsentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  status?: T;
  order?: T;
  slug?: T;
  title?: T;
  shortDescription?: T;
  description?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  audience?: T;
  ctaLabel?: T;
  curriculum?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  pricingType?: T;
  price?: T;
  priceRangeMin?: T;
  priceRangeMax?: T;
  currency?: T;
  duration?: T;
  scheduleInfo?: T;
  enrollmentState?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  status?: T;
  order?: T;
  relatedCourse?: T;
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  status?: T;
  consentObtained?: T;
  consentNote?: T;
  relatedCourse?: T;
  authorName?: T;
  authorRole?: T;
  quote?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  status?: T;
  assignedTo?: T;
  consultationAt?: T;
  source?: T;
  name?: T;
  phone?: T;
  email?: T;
  preferredLanguage?: T;
  interestedCourse?: T;
  message?: T;
  internalNotes?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  privacyConsentAt?: T;
  privacyPolicyVersion?: T;
  marketingConsent?: T;
  marketingConsentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}